project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  page-navigation: true
  title: "GeoEpi"
  site-url: https://geoepi.github.io
  open-graph: true
  favicon: images/geoepi_logo_xsm.png
  navbar:
    logo: images/geoepi_logo_sm.png
    title: "GeoEpi"
    right:
      - href: index.qmd
        text: Home
      - href: pindex.qmd
        text: Research
      - href: https://geoepi.github.io/Notebook/
        text: Notebook
      - href: about.qmd
        text: About
      - text: Connect
        menu:
          - icon: github
            href: https://github.com/geoepi
            text: "Group GitHub Site"
          - icon: octagon
            href: https://osf.io/hf8t2/
            text: "Open Science Framework"
          - icon: envelope
            href: mailto:john.humphreys@usda.gov
            text: "john.humphreys@usda.gov"
      - icon: github
        menu:
          - text: Site Source Code
            url:  https://github.com/geoepi/geoepi.github.io
          - text: Report Site Issue
            url:  https://github.com/geoepi/geoepi.github.io/issues
  page-footer:
    border: false
    left: "Published with [Quarto](https://quarto.org/) v1.2.335"
    right: "© 2024 [John Humphreys](/about) | [MIT License](/license)"
        
format:
  html:
    theme:
      light: scss/light.scss
      dark:  scss/dark.scss
    revealjs:
      logo: images/geoepi_logo_xsm.png
      css: scss/styles.css
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox
    df-print: kable

editor: visual