project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - pindex.qmd
    - publications.qmd
    - about.qmd
    - "research/*/index.qmd"
    - "projects/*/index.qmd"

execute:
  freeze: auto

website:
  page-navigation: true
  title: "GeoEpi Research Group"
  site-url: https://geoepi.github.io
  open-graph: true
  favicon: images/geoepi_logo_xsm.png
  navbar:
    logo: images/geoepi_logo_sm.png
    title: "GeoEpi"
    right:
      - href: index.qmd
        text: Home
      - href: pindex.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: about.qmd
        text: About
      - href: https://github.com/geoepi/geoepi-hub
        text: GeoEpi Hub
      - href: https://geoepi.github.io/geoepi-notebook/
        text: GeoEpi Lab Book
      - text: Connect
        menu:
          - icon: github
            href: https://github.com/geoepi
            text: "GeoEpi GitHub organization"
          - icon: octagon
            href: https://osf.io/hf8t2/
            text: "Open Science Framework"
          - text: Site Source Code
            href: https://github.com/geoepi/geoepi.github.io
          - text: Report Site Issue
            href: https://github.com/geoepi/geoepi.github.io/issues
  page-footer:
    border: false
    left: "GeoEpi Research Group"
    right: "[GitHub](https://github.com/geoepi) · [Hub](https://github.com/geoepi/geoepi-hub) · [Lab Book](https://geoepi.github.io/geoepi-notebook/) · [Site source](https://github.com/geoepi/geoepi.github.io)"

format:
  html:
    theme: scss/light.scss
    link-external-icon: false
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: github
    df-print: kable

editor: visual
